---
title: "Day 8"
author: "J Lacasa"
date: "2026-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(emmeans)
library(multcomp)
```

# Load data, little check to make sure everything is loaded well
```{r}
url <- "https://raw.githubusercontent.com/stat720/summer2025/refs/heads/main/data/blood_study_pigs.csv"
df_pigs <- read.csv(url)
nrow(df_pigs)
df_pigs %>% 
  ggplot(aes(paste(Trt, Day), Serum_haptoglobin_mg.dL))+
  geom_point()
```
# Fit CRD model to the data 

$$y_{ijk} = \mu + T_j + D_k + (TD)_{jk} + \varepsilon_{ijk}, \ \varepsilon_{ijk} \ \text{iid}\sim \ N(0, \sigma^2) $$ 

```{r}
df_pigs$Day <- as.factor(df_pigs$Day)

model1 <- lm(Serum_haptoglobin_mg.dL ~ Trt * Day, data = df_pigs)
summary(model1)
#model checks
plot(model1$fitted.values, model1$residuals)
car::qqPlot(model1)
```


```{r}
16 * 6 * 2 - (6*2)
```



```{r}
# anova
car::Anova(model1, type = 2)
```

# Estimated Mg means
```{r}
(means_all <- emmeans(model1, ~ Day:Trt))
plot(means_all)
```


```{r}
sigma2_hat <- sigma(model1)^2

sigma2_hat <- 36751 / 180


n_reps <- n_distinct(df_pigs$Pen) / n_distinct(df_pigs$Trt)

sqrt(2*sigma2_hat/n_reps)
```

## No interaction

```{r}
model2 <- lm(Serum_haptoglobin_mg.dL ~ Trt + Day, data = df_pigs)

plot(model2$fitted.values, model2$residuals)


plot(emmeans(model2, ~Day:Trt))
```


```{r}
sigma(model1)
sigma(model2)
```



# What if we're interested in less comparisons
```{r}
means_38 <- emmeans(model1, ~ Trt:Day, at = list(Day = "38"))
cld(means_38)
```
```{r}
6*16
```

```{r}
model3 <- lm(Serum_haptoglobin_mg.dL ~ Trt*Day, 
             data = df_pigs |> filter(Trt %in% c("A", "B", "C")))

emmeans(model3, ~ Trt:Day)
```


