---
title: "STAT 720 -- Anlyzing the muffin experiment"
author: "J Lacasa"
date: "2026-07-15"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lme4)
library(emmeans)
```

```{r}
url <- "https://raw.githubusercontent.com/stat720/summer2026/refs/heads/main/data/stat720_muffins_2026.csv"
dat <- read.csv(url) |>
  filter(!is.na(height_cm)) |> 
  mutate(block = as.factor(block) |> as.numeric()) |> 
  filter(block %in% c(1, 2,  6:10))
  # filter( height_cm>4)

unique(dat$block)

dat |> 
  group_by(block, recipe) |> 
  summarise(n())
```



```{r}
dat |> 
  ggplot(aes(recipe, height_cm))+
  geom_point(aes(color = factor(block)))+
  labs(y = "Height (cm)")+
  theme(aspect.ratio = .3)
```


```{r}
m <- lmer(height_cm ~ 1 + recipe + (1|block) + (1|block:recipe), 
     data = dat)
```

```{r}
(means <- emmeans(m, ~recipe, contr = list(c(1, -1, 0), c(1, 0, -1), c(0, 1, -1))))
```

```{r}
as.data.frame(means$emmeans) |> 
  ggplot(aes(recipe, emmean))+
  geom_point()+
  geom_errorbar(aes(ymin = emmean-SE, ymax = emmean+SE), width = 0)
```









