# Applied Linear Mixed Models II     
June 24th, 2025  

## Review: Designs 

When we model data generated by designed experiments, we typically put the information from the treatment as affecting the mean ($\mu$), while the elements from the design (topographical, design, or the logistics of the experiment) indicate which observations are independent and which ones are not. 

- Completely randomized designs: independent EUs that allow us to make the assumption of independence. 
- Randomized complete block designs: *groups* of similar EUs: the assumption of independence does not stay the same anymore, but we can say that observations from a same block are all related to each other.    
- Other types of designs: split-plot and strip-plot 

### Let's look at the anova table  

```{r echo=FALSE, message=FALSE, warning=FALSE}
t_trt <- data.frame(Source = c("Factor A", "Factor B", "A x B", "Parallels", "Total"),
                    df = c("a-1", "b-1", "(a-1)(b-1)", "N-(ab)", "N-1"))
knitr::kable(t_trt, caption = "Treatment ANOVA for a two-way treatment structure")
```

## Tomorrow  

- Zoom classes -- we will use the link for the office hours 

